# extra_css:
#   - stylesheets/extra.css

theme:
  palette:
    primary: custom
  # logo: logo.png
  # favicon: logo.png
  name: "material"
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - content.code.annotate
    - toc.follow
    # - navigation.instant
    - content.code.copy
    - navigation.top
    # - navigation.tabs

plugins:
- mike:
    version_selector: true
    deploy_prefix: public
    css_dir: css
# - mkdocs-versioning:
#     version: 0.3.0
- search
# use docs/gen_ref_pages_standalone.py to generate reference pages
# and be compatible with mkdocs-static-i18n
# - gen-files:
#     scripts:
#     - docs/gen_ref_pages.py
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_if_no_docstring: false
          merge_init_into_class: true

    # watch:
    # - fordead/
# - literate-nav:
#     nav_file: SUMMARY.md
# - section-index # systamtically makes an index at the begining of each section
# - mermaid2
- autorefs
- i18n:
    docs_structure: suffix
    languages:
        - locale: en
          name: English
          build: true
          default: true
          # link: /fordead/
        - locale: fr
          name: Français
          build: true
          # link: /fordead/fr/


# Customization
extra:
  feature:
    tabs: true
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fordead/fordead_package
  version:
    provider: mike

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
      title: On this page
      toc_depth: 1-3
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mdx_breakless_lists
  
# rest of the navigation..
site_name: fordead
repo_name: fordead
repo_url: https://gitlab.com/fordead/fordead_package
extra_css:
  - 'css/style.css'
# edit_uri: '-/edit/master/'
# site_url: http://localhost:8000/public
site_url: https://fordead.gitlab.io/fordead_package